swagger: '2.0'

info:
  description: APIs for managing Video assets on S3
  version: 0.0.1
  title: Video CMS

basePath: /

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:

  /health:
    get:
      summary: returns OK
      responses:
        '200':
          description: health check successful

  /video:
    post:
      summary: 'Creates a new video.'
      operationId: videoCreate
      parameters:
      - name: seed
        in: body
        description: 'The video input.'
        required: true
        schema:
          $ref: '#/definitions/Video'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Video'
    get:
      summary: 'Returns all videos.'
      operationId: videosList
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VideosList'

  /video/{video_id}:
    get:
      summary: 'Returns an existing video by its ID.'
      operationId: videoRead
      parameters:
      - name: video_id
        in: path
        description: 'The ID of the video to be read.'
        required: true
        type: string
        format: uuid
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Video'
    delete:
      summary: 'Delete an existing video by its ID.'
      operationId: videoDelete
      parameters:
      - name: video_id
        in: path
        description: 'The ID of the video to be deleted'
        required: true
        type: string
        format: uuid
      responses:
        '204':
          description: OK
    put:
      summary: 'Update an existing video by its ID.'
      operationId: videoUpdate
      parameters:
      - name: video_id
        in: path
        description: 'The ID of the video to be updated.'
        required: true
        type: string
        format: uuid
      - name: seed
        in: body
        description: 'The updated video input.'
        required: true
        schema:
          $ref: '#/definitions/Video'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Video'

definitions:

  VideosList:
    description: 'The list of videos.'
    type: array
    items:
      $ref: '#/definitions/Video'

  Video:
    description: 'Video data.'
    type: object
    properties:
      id:
        description: 'Video identifier.'
        type: string
      name:
        description: 'The name of the video.'
        type: string
      updated_at:
        description: 'The date and time that the video was last updated.'
        type: string
        format: date-time
      created_at:
        description: 'The date and time that the video was created.'
        type: string
        format: date-time
